# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# The bot is less goofy with this off.  We don't need poems in the summary...
have_fun: false
code_review:
  disable: false
  # Set to -1 for unlimited comments.
  max_review_comments: 6
  # For now, use the default of MEDIUM for testing. Based on desired verbosity,
  # we can change this to LOW or HIGH in the future.
  comment_severity_threshold: MEDIUM
  pull_request_opened:
    # Explicitly set help to false in case the default changes in the future, as
    # having a help message on every PR would be spammy.
    help: false
    # These tend to be verbose, and since we expect PR authors to clearly
    # describe their PRs this would be at best duplicative.
    summary: false
